name: web-saas
version: doco.v1
working_dir: compose/web-saas
compose_files:
  - docker-compose.yml
  - docker-compose.prod-storage.yml
env_files:
  - .env.prod
force_image_pull: true
remove_orphans: true
timeout: 300
